### PR TITLE
Tutorial Updates

### LINKED ISSUE #13: OpenFoam 11 Header Updates
We should probably update all headers the the OF-11 specific copyright. Please also keep the ORNL copyright header for original code

_Originally posted by @colemanjs in https://github.com/kincaidkc/AdditiveFOAM/pull/10#discussion_r1484682235_

### LINKED ISSUE #16: Clean / Combine Tutorials
To reduce the number of tutorials, can we combine AMB2018-02-B and AMB2018-02-B-AMR?
Can you rename the "5x5pad" tutorial to AMB2018-01-L7 and rename "constant/five_mm_square" to "constant/scan_path_even"

For the AMB2018-02-B tutorial, please add a link to the description in the Allrun or a readme (https://www.nist.gov/ambench/amb2018-02-description)

Please to the same for the new AMB2018-01-L7 tutorial (https://www.nist.gov/ambench/amb2018-01-description)

_Originally posted by @colemanjs in https://github.com/kincaidkc/AdditiveFOAM/issues/10#issuecomment-1936421856_

The 5x5 pad tutorial was cleaned, but the single scan AMB-2018-02-B and AMB-2018-02-B-AMR cases need to be combined and cleaned.

### PR DESCRIPTION
**Pull request by kincaidkc**
This PR updates the tutorial suite reflecting recent changes. Notably, the `AMB-2018-02-B` and `AMB-2018-02-B-AMR` cases were combined into a single new case using the new `refinementController` class logic. References were added to the `Allrun` files for each AMB challenge problem, and the tutorial file headers were all updated to OpenFOAM version 11.

Closes #13, closes #16

### CODE REVIEW

**Comment by colemanjs** [comment]
Is it possible in the AMB2018-02-B tutorial to have one with and one without AMR in the same folder? This is the tutorial that the CI uses, so I would like to try and be consistent having AMR as an option. If not, I guess we can revert back to independent tutorials, but keep the updated headers in this PR

**Comment by kincaidkc** [comment]
> Is it possible in the AMB2018-02-B tutorial to have one with and one without AMR in the same folder? This is the tutorial that the CI uses, so I would like to try and be consistent having AMR as an option. If not, I guess we can revert back to independent tutorials, but keep the updated headers in this PR

 Can the CI modify files before running? If it does `mv dynamicMeshDict dynamicMeshDict_` the case will run without AMR

**Comment by colemanjs** [comment]
> > Is it possible in the AMB2018-02-B tutorial to have one with and one without AMR in the same folder? This is the tutorial that the CI uses, so I would like to try and be consistent having AMR as an option. If not, I guess we can revert back to independent tutorials, but keep the updated headers in this PR
> 
> Can the CI modify files before running? If it does `mv dynamicMeshDict dynamicMeshDict_` the case will run without AMR

In that case, can we just change dynamicMeshDict to dynamicMeshDict.orig in the basic tutorial? Then CI won't need to change and we can put a comment in Allrun showing how to run AMR with cp -r  dynamicMeshDict.orig   dynamicMeshDict

**Comment by kincaidkc** [comment]
> In that case, can we just change dynamicMeshDict to dynamicMeshDict.orig in the basic tutorial? Then CI won't need to change and we can put a comment in Allrun showing how to run AMR with cp -r dynamicMeshDict.orig dynamicMeshDict

Done but I remembered that the `decomposeParDict` is also using Zoltan which people may not have installed. What do you think is the best way to handle the different distribution schemes?

**Comment by colemanjs** [comment]
> > In that case, can we just change dynamicMeshDict to dynamicMeshDict.orig in the basic tutorial? Then CI won't need to change and we can put a comment in Allrun showing how to run AMR with cp -r dynamicMeshDict.orig dynamicMeshDict
> 
> Done but I remembered that the `decomposeParDict` is also using Zoltan which people may not have installed. What do you think is the best way to handle the different distribution schemes?

I think that we can just follow the OpenFOAM example, where Zoltan is commented out in decomposeParDict. We can add a note in the Allrun of what it is for. The changes are getting complicated enough that we might want READMEs for the tutorials....

**Comment by kincaidkc** [comment]
> I think that we can just follow the OpenFOAM example, where Zoltan is commented out in decomposeParDict. We can add a note in the Allrun of what it is for. The changes are getting complicated enough that we might want READMEs for the tutorials....

Commented out the AMR related entries and added a README explaining changes for AMR

**Pull request merged**
